name: Build and Test
on: [push, pull_request]
permissions:
  contents: read
jobs:
  build-go:
    name: Go CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.24', '1.25']
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@acb598e5ddbc6f68a970c5da0688d2f3a9f04d05 # v1.6.0
        with:
          packages: git-restore-mtime libgtk-3-dev libwebkit2gtk-4.1-dev
          version: 1.0

      - name: Check out source
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: ${{ matrix.go }}
          cache: true

      # Restore original file modification times for test cache reasons
      - name: restore timestamps
        run: git restore-mtime

      - name: Install Linters
        run: "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.6.2"

      - name: Test
        run: |
          mkdir -p client/webserver/site/dist
          touch -t 2306151245 client/webserver/site/dist/placeholder
          ./run_tests.sh
  build-js:
    name: Build JS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 24.x]
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Use nodejs ${{ matrix.node-version }}
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm clean-install
      working-directory: ./client/webserver/site
      run: npm ci
    - name: npm run lint
      working-directory: ./client/webserver/site
      run: npm run lint
    - name: npm run build
      working-directory: ./client/webserver/site
      run: npm run build

  lint-docs:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: DavidAnson/markdownlint-cli2-action@30a0e04f1870d58f8d717450cc6134995f993c63 # v21.0.0
      continue-on-error: true
      with:
        globs: |
          *.md
          docs/**/*.md
