name: Build and Test
on: [push, pull_request]
permissions:
  contents: read
jobs:
  build-go:
    name: Go CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.19', '1.20']
    steps:
      - name: Set up Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 #v3.5.0
        with:
          go-version: ${{ matrix.go }}

      - name: Check out source
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c #v3.3.0
      - name: Install Linters
        run: "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.51.1"

      - name: Test
        env:
          GO111MODULE: "on"
        run: |
          mkdir -p client/webserver/site/dist
          touch client/webserver/site/dist/placeholder
          sudo apt -y install libgtk-3-dev libwebkit2gtk-4.0-dev
          ./run_tests.sh
  build-js:
    name: Build JS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c #v3.3.0
    - name: Use nodejs ${{ matrix.node-version }}
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c #v3.6.0
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm clean-install
      working-directory: ./client/webserver/site
      run: npm ci
    - name: npm run lint
      working-directory: ./client/webserver/site
      run: npm run lint
    - name: npm run build
      working-directory: ./client/webserver/site
      run: npm run build
  lint-docs:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c #v3.3.0
    - uses: DavidAnson/markdownlint-cli2-action@d57f8bd57670b9c1deedf71219dd494614ff3335 #v8
      continue-on-error: true
      with:
        globs: |
          *.md
          docs/**/*.md
      
