name: Build and Test
on: [push, pull_request]
permissions:
  contents: read
jobs:
  build-go:
    name: Go CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.22', '1.23']
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@a6c3917cc929dd0345bfb2d3feaf9101823370ad #v1.4.2
        with:
          packages: git-restore-mtime libgtk-3-dev libwebkit2gtk-4.0-dev
          version: 1.0

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 #v5.0.2
        with:
          go-version: ${{ matrix.go }}

      - name: Check out source
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
        with:
          fetch-depth: 0
      # Restore original file modification times for test cache reasons
      - name: restore timestamps
        run: git restore-mtime
      - name: Install Linters
        run: "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.60.2"
      - name: Use test and module cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 #v4.0.2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-test-${{ matrix.go }}-${{ github.sha }}
          restore-keys: go-test-${{ matrix.go }}

      - name: Test
        env:
          GO111MODULE: "on"
        run: |
          mkdir -p client/webserver/site/dist
          touch -t 2306151245 client/webserver/site/dist/placeholder
          ./run_tests.sh
  build-js:
    name: Build JS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
    - name: Use nodejs ${{ matrix.node-version }}
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b #v4.0.3
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm clean-install
      working-directory: ./client/webserver/site
      run: npm ci
    - name: npm run lint
      working-directory: ./client/webserver/site
      run: npm run lint
    - name: npm run build
      working-directory: ./client/webserver/site
      run: npm run build

  lint-docs:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
    - uses: DavidAnson/markdownlint-cli2-action@b4c9feab76d8025d1e83c653fa3990936df0e6c8 #v16.0.0
      continue-on-error: true
      with:
        globs: |
          *.md
          docs/**/*.md
      
